name: Create release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install dependency and build
        run: |
          yarn install
          yarn build

      - name: Set runtime cache version
        run: |
          python -c "sw=open('dist/sw.js',mode='r',encoding='utf-8').read();open('dist/sw.js',mode='w',encoding='utf-8').write(sw.replace('{tag}', '${{ github.ref_name }}'))"

      - name: Taping dist
        run: python tape.py ${{ github.sha }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist-*.zip
